no_color_sigmoid: False
render_only: False
render_test: True
render_factor: 0
testskip: 8
deepvoxels_shape: greek
blender_white_background: True
blender_half_res: False
llff_factor: 8
llff_no_ndc: False
llff_lindisp: False
llff_spherify: False
llff_hold: False
print_interval: 100
checkpoint_interval: 10000
render_testset_interval: 10000
render_video_interval: 100000000 # deactivated by default
chunk_size: 32768
network_chunk_size: 65536
rng_seed: 0
use_same_initialization_for_all_networks: False
use_initialization_fix: False


perturb: 1.0
raw_noise_std: 0.0
num_samples_per_ray: 192
num_importance_samples_per_ray: 0
model_type: multi_network
initial_learning_rate: 0.0005
random_direction_probability: -1 # deactivated
von_mises_kappa: -1 # deactivated
view_dependent_dropout_probability: -1 # deactivated
